name: ayarla
description: Ayarla - Yeni Nesil, Akıllı Randevu Danışmanı

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2
  cupertino_icons: ^0.1.2
  path_provider: ^1.6.17
  font_awesome_flutter: ^8.10.0
  photo_view: ^0.9.2
  provider: ^4.3.2+2
  #  mailer: ^4.0.0
  flutter_week_view: ^1.0.0+1
  location: ^3.0.2
  google_maps_flutter: ^1.0.6
  url_launcher: ^5.7.10
  rating_dialog: ^2.0.0
  marquee: ^2.0.0
  carousel_slider: ^3.0.0
  image: ^2.1.19
  modal_bottom_sheet: ^1.0.0+1
  flutter_svg: ^0.19.3
  image_picker: ^0.6.6+5
  share: ^2.0.1
  mailer2: ^1.2.5
  badges: ^1.2.0
  menu_button: ^1.4.1
  google_maps_place_picker: ^1.0.1
  flutter_slidable: ^0.5.7
  syncfusion_flutter_sliders: ^19.1.55-beta
  fluro: ^1.7.8
  url_strategy: ^0.2.0
  #firebase imports
  firebase_database: ^6.0.0
  firebase: ^7.3.3
#  firebase_messaging: ^8.0.0-dev.15
  firebase_dynamic_links: ^0.5.1
  firebase_core: ^0.7.0
#  firebase_analytics: ^7.0.0
  #map
  mapbox_gl: ^0.0.1
  mapbox_search: ^2.1.0
  mapbox_search_flutter: any
#  premium packages
  stories_for_flutter: ^0.1.8
#  story: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/new/

  fonts:
    - family: Courier
      fonts:
        - asset: fonts/CourierPrime-Bold.ttf

    - family: Round_Regular
      fonts:
        - asset: fonts/Typo_Round_Regular_Demo.otf


    - family: Round_Bold
      fonts:
        - asset: fonts/Typo_Round_Bold_Demo.otf